### ISSUE TITLE
Vesktop on Hyprland Arch Linux support.

### ISSUE THREAD

**Issue by iceeburr** [FurryOfficial/TranslucencePlus#1]
# The Issue
Currently if you try to use it the background will just turn white and you won't see anything. The theme itself is fully functional, the only issue being the transparency effect for no background configurations is broken. Take a look:
![image](https://github.com/MeowIce/TranslucencePlus/assets/85520957/8a016191-74de-46ab-911b-5295f0ffd8cc)
## Failed Attempts
Is it me that did something wrong, or the theme is just broken?
I have enabled the transparent background experiment for Vencord.
![image](https://github.com/MeowIce/TranslucencePlus/assets/85520957/8b758f97-6f46-4220-9585-3894dc4ed1dc)
Only change in the css I've done `--app-bg: rgba(0,0,0,0);`.
I tried most of the stuff that were in this [Reddit post](https://www.reddit.com/r/BetterDiscord/comments/1065blb/using_mica_for_everyone_for_transparent_discord/), but it didn't work.
## If anyone has a solution please let me know.

*Edit: here is an example of how the "translucent blurry" effect should look like*
![image](https://github.com/MeowIce/TranslucencePlus/assets/85520957/dd86077a-48e9-432b-9955-f0a4a84ca1fd)

**Comment by iceeburr** [comment]
# Small Update

Turns out the theme works, but partly. When launching the Discord app it has a loading animation in it's own window, after that the main window will pop up. That loading one has the blurry effect and I confirmed it.
Here is how it looks:
With Theme:
![image](https://github.com/MeowIce/TranslucencePlus/assets/85520957/fdeca3fc-6865-4369-8a7a-c5d0a68fa02d)
Without Theme:
![image](https://github.com/MeowIce/TranslucencePlus/assets/85520957/ba23430c-72ef-466d-b8e7-bd787efcbf7a)

## Side Notes
I tested if `blurls = vencorddesktop` will do anything, turns out it doesn't.
Blurls is a setting in the hyprland config which should "imitate" what blur my shell does on gnome, but here it does nothing. Blurls is also equal to `layerrule = blur, application` from what I tested.

**Comment by iceeburr** [comment]
# Solution
Don't use Vencord.
Yes, simple as that. The developer has refused to fix it and an issue about this has already been made before.
Vencord/Vesktop do not support transparent backgrounds, or the functionality broke after a Discord update.
[Check this issue to see more.](https://github.com/Vencord/Vesktop/issues/252)
## More in-depth explanation on how to get it working.
Since Vencord won't support transparent backgrounds you will have to use a different Discord client.
I have tested it with the base Discord client. Might work on different ones as well.
On Arch simply do these if you haven't:
Install the official Discord client - `pacman -S discord`. For other versions use the AUR.
Open the client once and login.
Install the betterdiscord installer from the AUR with yay helper - `yay -S betterdiscord-installer`
Open the installer - `betterdiscord-installer`
From there do your normal betterdiscord install.
In betterdiscord settings make sure to enable transparent windows and restart the client.

Side note - if any vencord developer is reading this, please take a few minutes to try and fix transparency on the vesktop client.
Closing this issue as "won't fix" since this is not an issue with the theme. The whole problem was with the Vesktop client and vencord itself.

Edit:
Forgot to include a screenshot. Background set to rgba(0,0,0,0.15).
![image](https://github.com/MeowIce/TranslucencePlus/assets/85520957/cd6c2375-9ecd-449d-a5f6-d52956afceed)
![image](https://github.com/MeowIce/TranslucencePlus/assets/85520957/382e67c7-ef75-4227-865e-6e43adc795b8)

**Comment by sneazy-ibo** [comment]
Is there a way to make the loading animation transparent and is it possible to make it blurry on mac sonoma? I can sadly only use a crystal clear background which ruins the aesthetic of it.
